### ISSUE TITLE
Investigate WebAssembly

### ISSUE THREAD

**Issue by rfk** [pypyjs/pypyjs#145]
The potential next iteration of asmjs is a new bytecode format called "WebAssembly":

  https://brendaneich.com/2015/06/from-asm-js-to-webassembly/

It's supposed to fix a bunch of the rough edges caused by asmjs's layering on top of js, e.g. parsing and filesize overheads and probably others as well.  We should do two things:

* Try it out and see if it's a better fit for us that talking asmjs
* See if we can use any of the lessons from pypyjs to influence design of WebAssembly

**Comment by kirbyfan64** [comment]
Maybe the RPython backend could output WebAssembly? It might cut down the loading time for pypy.vm.js.

**Comment by rfk** [comment]
Definitely, I think the loading time will be the first big win here.  Hopefully we can get initial support almost-for-free by just asking emscripting to spit out the new format.

Longer term, Brendan's post suggests that WebAssembly will eventually support feature that will be really useful for building a dynamic language interpreter: dynamic linking (for easier loading modules at runtime) and call/cc (for easier suspension of the VM, allowing async file loading etc).  I haven't digested all the news yet, but this WebAssembly thing seems like a pretty big deal.

**Comment by rfk** [comment]
Also this: https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#platform-independent-just-in-time-compilation

**Comment by empyrical** [comment]
Would be sweet if the work on pypyjs also enabled the other RPython based VMs to work with WebAssembly!

**Comment by jedie** [comment]
*(From #146 written by "IronManMark20")*


I was scrolling through /r/python when I read [this interesting article](http://techcrunch.com/2015/06/17/google-microsoft-mozilla-and-others-team-up-to-launch-webassembly-a-new-binary-format-for-the-web/?ncid=rss&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Techcrunch+%28TechCrunch%29). Essentially, WebKit will begin supporting binary blobs of C/C++ code. Therefore, I think PyPyJS should use WebAssembly, once it releases (still pre-release). To quote the article:

> it’s much faster for the engine to decode the binary format (up to 23x faster in the current prototype) than parsing asm.js code, for example.

A 23x speedup sounds pretty nice to me, and we are already generating C++ files from the rpython bit, right?

And finally, it won't require much porting (taken from the article):
>and developers will be able to use the same Emscripten tool for WebAssembly as they use for compiling asm.js code today

All in all, good news! Do you think PyPyJS will target WebAssembly?

**Comment by IronManMark20** [comment]
Sorry I didn't find this issue. Thanks @jedie for crossposting. I hope they get the MVP done soon.

**Comment by jedie** [comment]
Some more Links:

* [WebAssembly FAQ](https://github.com/WebAssembly/design/blob/master/FAQ.md)
* [WebAssembly High-Level Goals](https://github.com/WebAssembly/design/blob/master/HighLevelGoals.md)
* [W3C WebAssemply Community Group](https://www.w3.org/community/webassembly/)

**Comment by rfk** [comment]
> Do you think PyPyJS will target WebAssembly?

Yes, definitely.  I am tremendously excited about WebAssembly :-)

**Comment by jedie** [comment]
How big/small is the normal pypy executable file? Does it really be so much smaller?

**Comment by kirbyfan64** [comment]
@jedie PyPy.js blew through 10 MB of my mobile data!

**Comment by rfk** [comment]
> How big/small is the normal pypy executable file?

It's still pretty big, it has a lot of stuff built straight into the executable.  But the encoding into asmjs certainly doesn't help.

**Comment by jedie** [comment]
10MB is similar to pypyjs.vm.js ... 
Maybe its also similar to compress ;)

**Comment by jedie** [comment]
Maybe **emterpreter** -> https://blog.mozilla.org/research/2015/02/23/the-emterpreter-run-code-before-it-can-be-parsed/ also interesting, before wasm is there?

**Comment by albertjan** [comment]
@jedie I've been fiddling with emterpreter a bit. And as it appears to do something along the same lines. wasm still wouldn't support the same stack operations as emterpreter does it won't be able to do async to synch stuff. In the end I think you'll end up with emterpreted code written in wasm. As far as I understand wasm is a binary representation of the javascript ast. With some magic sauce :smile: 

An emterpreted build of pypyjs is 25MB uncompressed. So that doesn't help with the size at all :smile:

**Comment by Erstwild** [comment]
Have there been any updates on examining this since Summer 2015?

**Comment by rfk** [comment]
I haven't looked into it any more since then, have been kinda waiting for a stable-ish release of wasm so we've got something concrete to target.

**Comment by ncoghlan** [comment]
Today's announcements of experimental support in browser nightlies suggests it may finally be stable enough to experiment with locally by ensuring the Emscripten and browser builds used are using the same iteration of the draft spec: https://hacks.mozilla.org/2016/03/a-webassembly-milestone/

**Comment by empyrical** [comment]
I don't think there's a fully functional direct WebAssembly compiler yet, but there's an asmjs->webassembly compiler called asm2wasm:

https://github.com/WebAssembly/binaryen/blob/master/README.md

**Comment by SimonBiggs** [comment]
I'm very interested in the progress of this.

**Comment by jedie** [comment]
https://lists.w3.org/Archives/Public/public-webassembly/2017Feb/0002.html

**Comment by SimonBiggs** [comment]
That is great news.

**Comment by tobig** [comment]
I just created #203 in an effort to build pypyjs with a recent version of emscripten. Unfortunately, this does not yet work as expected.

Out of interest, what would be needed to make webassembly support happen? Would switching the output language of emscripten enough (modulo smaller fixes here and there) or do you expect larger changes in pypy itself?

**Comment by tobig** [comment]
Just tried it out. Just passing '-s BINARYEN=1' to emscripten to ask for wasm does not work. I get:

```
[platform:WARNING] INFO:root:generating system library: wasm-libc.bc... (this will be cached in "/var/cache/emscripten/cache/asmjs/wasm-libc.bc" for subsequent builds)
[platform:WARNING] INFO:root: - ok
Traceback (most recent call last):
  File "<builtin>/app_main.py", line 75, in run_toplevel
  File "./deps/pypy/rpython/bin/rpython", line 20, in <module>
    main()
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/translator/goal/translate.py", line 217, in main
    targetspec_dic, translateconfig, config, args = parse_options_and_load_target()
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/translator/goal/translate.py", line 156, in parse_options_and_load_target
    targetspec_dic = load_target(targetspec)
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/translator/goal/translate.py", line 98, in load_target
    mod = __import__(specname)
  File "./deps/pypy/pypy/goal/targetpypystandalone.py", line 13, in <module>
    from rpython.rlib import rthread
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/rlib/rthread.py", line 1, in <module>
    from rpython.rtyper.lltypesystem import rffi, lltype, llmemory
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/rtyper/lltypesystem/rffi.py", line 552, in <module>
    NUMBER_TYPES = setup()
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/rtyper/lltypesystem/rffi.py", line 541, in setup
    names = populate_inttypes()
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/rtyper/lltypesystem/rffi.py", line 535, in populate_inttypes
    platform.populate_inttypes(populatelist)
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/rtyper/tool/rfficache.py", line 83, in populate_inttypes
    sizes = sizeof_c_types(names_c, **kwds)
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/rtyper/tool/rfficache.py", line 47, in sizeof_c_types
    assert len(lines) == len(typenames_c)
AssertionError
```

**Comment by albertjan** [comment]
I think you'll need @rfk 's guidance on this one 😁

**Comment by albertjan** [comment]
I think it means the types in your build system arent the same as they are on your os. Or what pypy expects.

**Comment by albertjan** [comment]
Try looking at the last command make did. you should be able to run that yourself if you exec into you docker box.

**Comment by tobig** [comment]
Yes, this needs further debugging. Getting a comment from @rfk what the high-level approach would look like will certainly help!

**Comment by rfk** [comment]
I'm sorry I haven't made much time for this project lately :-(

But I am in fact reading all these github notifications when they show up in m inbox; I'll try to carve out an evening to dive in soon...

I think you're on the right track here @tobig, but will need to dig into the details of what emscripten is outputting when it compiles stuff.  IIRC that `rfficache.py` basically tries to compile a bunch of little helper programs that print out the sizes of various types etc in the system.  It's possible that these helper programs are not running correctly, printing out an error rather than the expected output, and that's causing the assertion failure you see there.

If you haven't tried it already, throwing a `print(lines)` right above that failure point might give a clue as to what's going wrong.  That's usually my strategy when trying to convince the rpython build chain to behave itself.

**Comment by tobig** [comment]
answer is "", lines is "[]", typenames_c is "['short', 'unsigned short', 'int', 'unsigned int', 'long', 'unsigned long', 'signed char', 'unsigned char', 'long long', 'unsigned long long', 'size_t', 'time_t', 'wchar_t', 'uintptr_t', 'intptr_t', 'void*', 'mode_t', 'pid_t', 'ssize_t', 'ptrdiff_t', 'int_least8_t', 'uint_least8_t', 'int_least16_t', 'uint_least16_t', 'int_least32_t', 'uint_least32_t', 'int_least64_t', 'uint_least64_t', 'int_fast8_t', 'uint_fast8_t', 'int_fast16_t', 'uint_fast16_t', 'int_fast32_t', 'uint_fast32_t', 'int_fast64_t', 'uint_fast64_t', 'intmax_t', 'uintmax_t']".

It seems that indeed the execution of the test program fails.

**Comment by rfk** [comment]
I haven't managed to try this out yet, still working on getting the latest build toolchain up and running on my machine.  But one thing that occurred to me from:

> Just tried it out. Just passing '-s BINARYEN=1' to emscripten to ask for wasm does not work. 

During the compilation process, pypy wants to generate and execute a bunch of little self-contained executables, which it runs to interrogate the system.  I seem to recall these working OK when generating JS output because they could be directly executed by the nodejs interpreter on the system, by this method:

  https://github.com/pypyjs/pypy/blob/d42c67374da065d99cdec44e433dd3adde780a8c/rpython/translator/platform/emscripten_platform/__init__.py#L117

I wonder if the generated wasm files are not executable in this way?

Where did you add the `-s BINARYEN=1` to emscripten?  My first attempt would have been in the link flags here:

  https://github.com/pypyjs/pypy/blob/d42c67374da065d99cdec44e433dd3adde780a8c/rpython/translator/platform/emscripten_platform/__init__.py#L94

But as I said, haven't gotten to the point of actually trying it out yet...

**Comment by rfk** [comment]
I've made a little bit of progress towards getting this up and running:

* https://github.com/pypyjs/pypyjs/pull/205
* https://github.com/pypyjs/pypy/pull/6

With those changes, I can compile the small "rematcher" test program via `make./build/rematcher-nojit.js` and have it run as WebAssembly.  It doesn't JIT or do anything fancy, but it runs!

The build generates a shell `.js` file, a binary `.wasm` file, and some fallback javascript `.asm.js` for browsers that don't support webassembly:

```
rfk@pomegranate:build(master *)$ ls rematcher-nojit-wasm.*
rematcher-nojit-wasm.asm.js  rematcher-nojit-wasm.js  rematcher-nojit-wasm.js.mem  rematcher-nojit-wasm.wasm  rematcher-nojit-wasm.wast
```

Running under node, it falls back to the plain javascript:

```
rfk@pomegranate:build(master *)$ node rematcher-nojit-wasm.js
trying binaryen method: native-wasm
no native wasm support detected
trying binaryen method: asmjs
binaryen method succeeded.
Generating 1000 strings of length 50 ...
Matching all strings against the regex...
Done!
Matching time for 1000 strings: 0.184000
Performed 5434.782158 matches per second.
```

Running under latest SpiderMonkey shell, it uses the webassembly version and it is much, much faster:

```
rfk@pomegranate:build(master *)$ ~/tmp/js rematcher-nojit-wasm.js
trying binaryen method: native-wasm
binaryen method succeeded.
Generating 1000 strings of length 50 ...
Matching all strings against the regex...
Done!
Matching time for 1000 strings: 0.047000
Performed 21276.626829 matches per second.
```

So, a good start :-)

Next steps we'll have to try include:

* Building the full pypy interpreter
* Adjusting `./src/pypyjs.js` to correctly load the new output files
* Benchmarking with and with wasm, and with and without the JIT enabled

Then, of course, there's the whole separate issue of updating the JIT backend to emit wasm at runtime...

I'll see about pushing an updated docker image for the build toolchain so that other folks can try it out, but it might take a while.  In the meantime you can build your own using `./tools/docker/build_toolchain_image.sh` if you're feeling adventurous.

**Comment by rfk** [comment]
> Running under node, it falls back to the plain javascript:

It's also worth noting that the fallback javascript is not quite valid asmjs, so it runs noticeably slower than the version produced by compiling straight to javascript.  I don't yet have a sense of how important that difference might be in practice.

**Comment by ncoghlan** [comment]
Regarding updating the current asm.js backend to emit wasm instead, it may be feasible to just push another turtle on the stack and use the `asm2wasm` compiler from https://github.com/WebAssembly/binaryen

**Comment by tobig** [comment]
Very very cool Ryan! It still so promising, but at the same time it
hightlights there is still quite some way to go. Still, very nice to see
the progress. Thanks a lot!

Best Tobias

**Comment by fuzzy76** [comment]
Since the average page size is 2 MB according to https://www.soasta.com/blog/page-bloat-average-web-page-2-mb/ it's not that much of a difference. I would also suggest using a common CDN such as https://www.jsdelivr.com for serving it.

**Comment by jedie** [comment]
Seems that there is a new project that tried to fix this problem by using MicroPython: https://github.com/pyscript/MicroPyScript
It's around 300k to download.

A DEMO is here: https://pyscript.net/tech-preview/micropython/index.html

See also: https://talkpython.fm/episodes/show/391/pyscript-powered-by-micropython
