### ISSUE TITLE
Question regading site, packages and module loading!

### ISSUE THREAD

**Issue by MaxMorais** [pypyjs/pypyjs#156]
Hello!

I'm doing small test with node-webkit and pypyjs in the client-side
I was looking for the proposed solution for `ImportError` in the readme, but something is going wrong

In the console on [website](http://pypyjs.org), when I try `import site` it's work fine, but I in my files I have the bellow code:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Kexy</title>
    <script src="kexy/pypy/Promise.min.js"></script>
    <script src="kexy/pypy/FunctionPromise.js"></script>
    <script src="kexy/pypy/pypy.js"></script>
    <script type="text/javascript">
        window.vm = new PyPyJS({
            stdout: function(data){
                console.log(data);
            }
        });
        vm.execfile = function(filename){
            return this.fetch(filename).then(function(xhr){
                var code = xhr.responseText;
                vm.findImportedNames(code).then((function(){
                    this.exec(code);
                }).bind(vm));
            });
        }
        vm.ready.then(function(){
            vm.execfile('test/__init__.py');
        });
    </script>
</head>
<body>
</body>
</html>
```
My `test/__init__.py` file have the below content

```python
from js import globals as js
import site
```

But I'm getting the bellow error in the console.

```python
Traceback (most recent call last):
  File "c callback", line 3, in <module>
  File "<string>", line 2, in <module>
ImportError: No module named site
```

I was not able to understand why I can import this package direct from the console but I'm not able to do the same in the `execfile`

**Comment by kirbyfan64** [comment]
Related to #137 and #150? Are you using the latest version from Git?

**Comment by MaxMorais** [comment]
Yes, @kirbyfan64 I'm using the latest version from pypyjs-release repository

I dont tryied build it from sources, can be a good idea?

**Comment by jedie** [comment]
IMHO the release repro must be updated. The real bug is fixed.

**Comment by rfk** [comment]
Yeah, sorry, I need to cut a new release after fixing this bug but I wanted to get #155 merged as well

**Comment by rfk** [comment]
I've made  v0.4.0 release which should include the fix for this, please try again

**Comment by MaxMorais** [comment]
I'll try it

2015-07-08 8:39 GMT-03:00 Ryan Kelly <notifications@github.com>:

> I've made v0.4.0 release which should include the fix for this, please try
> again
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pypyjs/pypyjs/issues/156#issuecomment-119547198>.
>



-- 

Best Regards.

Maxwell Morais
Python Developer powered by Webnotes framework <3
+55 11 954329659
